# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 16
          # you can set branches for semantic-release above v16.
          branches: |
            [
              {
                name: 'main',
                prerelease: false,
                channel: 'latest'
              },
              {
                name: '[0-9].[0-9]',
                prerelease: false,
                channel: 'latest'
              },
              {
                name: 'dev/*',
                prerelease: true,
                channel: 'beta'
              },
              {
                name: 'experimental/*',
                prerelease: true,
                channel: 'experimental'
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
